---
- name: get openssh src
  get_url:
    url=http://download.openpkg.org/components/cache/openssh/openssh-{{ openssh_version }}.tar.gz
    dest=/tmp/
    sha256sum=48c1f0664b4534875038004cc4f3555b8329c2a81c1df48db5c517800de203bb

- name: get openssh patch
  get_url:
    url=http://download.openpkg.org/components/cache/openssh/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff.gz
    dest=/tmp/
    sha256sum=682b4a6880d224ee0b7447241b684330b731018585f1ba519f46660c10d63950

- name: untar openssh src
  unarchive:
    src=/tmp/openssh-{{ openssh_version }}.tar.gz
    dest=/tmp/ 
    copy=no 
    creates=/tmp/openssh-{{ openssh_version }}
  register: openssh_src

- name: untar openssh patch
  command: /bin/gzip -d /tmp/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff.gz
    chdir=/tmp/ 
    creates=/tmp/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff 

- name: apply openssh patch
  command: /usr/bin/patch -i /tmp/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff
    chdir=/tmp/openssh-{{ openssh_version }}/
  register: openssh_patched
  when: openssh_src.changed

- name: remove unused openssh distros
  file: 
    path=/tmp/openssh-{{ openssh_version }}/contrib/{{item}}
    state=absent
  with_items:
    - aix
    - caldera
    - cygwin
    - hpux
    - solaris
    - suse

- name: spec file | set no_gnome_askpass
  lineinfile:
    dest=/tmp/openssh-{{ openssh_version }}/contrib/redhat/openssh.spec
    regexp="^%define no_gnome_askpass"
    line="%define no_gnome_askpass 1"
    insertafter="^#%define no_gnome_askpass"

- name: spec file | set no_x11_askpass
  lineinfile:
    dest=/tmp/openssh-{{ openssh_version }}/contrib/redhat/openssh.spec
    regexp="^%define no_x11_askpass"
    line="%define no_x11_askpass 1"
    insertafter="^#%define no_x11_askpass"

- name: spec file | set build6x
  lineinfile:
    dest=/tmp/openssh-{{ openssh_version }}/contrib/redhat/openssh.spec
    regexp="^%define build6x"
    line="%define build6x 1"
    insertafter="^#%define build6x"

- name: spec file | set build6x for rhel6+
  lineinfile:
    dest=/tmp/openssh-{{ openssh_version }}/contrib/redhat/openssh.spec
    regexp="^%\{\?build_6x:%define build6x"
    line="%{?build_6x:%define build6x 0}"
    insertafter="^#%\{\?build_6x:%define build6x"

- name: create archive of patched openssh
  command: tar czf openssh-{{ openssh_version }}.tar.gz openssh-{{ openssh_version }}/
    chdir=/tmp/
  when: openssh_patched.changed

- name: creating patched openssh rpm
  command: rpmbuild -tb --clean openssh-{{ openssh_version }}.tar.gz 
    chdir=/tmp/
  when: openssh_patched.changed

- name: install patched openssh packages
  command: /bin/rpm -Uvh --force /root/rpmbuild/RPMS/x86_64/*.rpm
  when: openssh_patched.changed

- name: configure HPN | sshd_config | set TcpRcvBufPoll
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^TcpRcvBufPoll"
    line="TcpRcvBufPoll yes"

- name: configure HPN | sshd_config | allow use of none cipher
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^NoneEnabled"
    line="NoneEnabled no"

- name: configure HPN | sshd_config | enable HPN performance
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^HPNDisabled"
    line="HPNDisabled no"

- name: configure HPN | sshd_config | set HPNBufferSize
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^HPNBufferSize"
    line="HPNBufferSize 16384"

- name: reload sshd configs
  service: name=sshd state=reloaded
