---
- name: install dtn packages
  yum: name={{ item }} state=latest
  with_items:
    - gcc 
    - glibc-devel 
    - krb5-devel 
    - make 
    - openssl 
    - openssl-devel 
    - pam
    - pam-devel 
    - patch 
    - rpm-build 
    - tcp_wrappers
    - tcp_wrappers-devel.x86_64 
    - zlib 
    - zlib-devel 

- name: get openssh src
  get_url:
    url="http://download.openpkg.org/components/cache/openssh/openssh-{{ openssh_version }}.tar.gz"
    dest=/usr/src/
    sha256sum=48c1f0664b4534875038004cc4f3555b8329c2a81c1df48db5c517800de203bb

- name: get openssh patch
  get_url:
    url="http://download.openpkg.org/components/cache/openssh/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff.gz"
    dest=/usr/src/
    sha256sum=682b4a6880d224ee0b7447241b684330b731018585f1ba519f46660c10d63950

- name: untar openssh src
  unarchive:
    src="/usr/src/openssh-{{ openssh_version }}.tar.gz"
    dest=/usr/src/ 
    copy=no 
    creates="/usr/src/openssh-{{ openssh_version }}/"
  register: openssh_src

- name: untar openssh patch
  command: /bin/gzip -d /usr/src/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff.gz
    chdir=/usr/src/ 
    creates=/usr/src/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff 

- name: apply openssh patch
  command: /usr/bin/patch -s -i /usr/src/openssh-{{ openssh_version }}-{{ openssh_patch }}.diff
    chdir=/usr/src/openssh-{{ openssh_version }}/
  when: openssh_src.changed

- name: remove unused openssh distros
  file: 
    path=/usr/src/openssh-{{ openssh_version }}/contrib/{{item}}
    state=absent
  with_items:
    - aix
    - caldera
    - cygwin
    - hpux
    - solaris
    - suse
