---
- name: setup a data transfer node (DTN) in OSDC
  hosts: os_ctrl
  tags: provision
  roles:
    - provision

- name: configure the new virtual machines
  hosts: dtn
  tags: configure
  roles: 
    - configure